# Generated by Django 5.1.7 on 2025-03-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRecuperarSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Data de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.CharField(editable=False, max_length=255, verbose_name='Usuario')),
                ('token', models.CharField(editable=False, max_length=255, verbose_name='Token')),
                ('data_utilizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de utilização')),
            ],
            options={
                'verbose_name': 'Token de recuperação de senha',
                'verbose_name_plural': 'Tokens de recuperação de senha',
                'ordering': ['usuario'],
            },
        ),
    ]
