# Generated by Django 5.1.7 on 2025-03-18 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TokenRecuperarSenha',
            new_name='Token_Recuperar_Senha',
        ),
    ]
