# Generated by Django 5.1.7 on 2025-03-23 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Data de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('nome_aglomerado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do aglomerado')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área total')),
                ('area_privativa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área privativa')),
                ('quartos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quartos')),
                ('banheiros', models.PositiveIntegerField(blank=True, null=True, verbose_name='Banheiros')),
                ('garagem', models.PositiveIntegerField(blank=True, null=True, verbose_name='Garagem')),
                ('suites', models.PositiveIntegerField(blank=True, null=True, verbose_name='Suítes')),
                ('lavabos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lavabos')),
                ('salas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salas')),
                ('area_servico', models.BooleanField(default=False, verbose_name='Área de serviço')),
                ('sacada', models.BooleanField(default=False, verbose_name='Sacada')),
                ('churrasqueira', models.BooleanField(default=False, verbose_name='Churrasqueira')),
                ('piscina', models.BooleanField(default=False, verbose_name='Piscina')),
                ('academia', models.BooleanField(default=False, verbose_name='Academia')),
                ('salao_festas', models.BooleanField(default=False, verbose_name='Salão de festas')),
                ('playground', models.BooleanField(default=False, verbose_name='Playground')),
                ('quadra', models.BooleanField(default=False, verbose_name='Quadra')),
                ('lavanderia', models.BooleanField(default=False, verbose_name='Lavanderia')),
                ('mobiliado', models.BooleanField(default=False, verbose_name='Mobiliado')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
                ('imagems', models.ImageField(blank=True, null=True, upload_to='imoveis', verbose_name='Imagens')),
                ('indicador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicador')),
                ('porcentagem', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentagem')),
                ('ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ref')),
                ('divulgar', models.BooleanField(default=True, verbose_name='Divulgar')),
                ('condicoes_pagamento', models.TextField(blank=True, null=True, verbose_name='Condições de pagamento')),
                ('documentos', models.TextField(blank=True, null=True, verbose_name='Documentos')),
                ('matricula', models.CharField(blank=True, max_length=255, null=True, verbose_name='Matrícula')),
                ('indicacao_fiscal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicação fiscal')),
                ('valor_condominio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do condomínio')),
                ('andar', models.PositiveIntegerField(blank=True, null=True, verbose_name='Andar')),
                ('elevador', models.BooleanField(default=False, verbose_name='Elevador')),
                ('portaria', models.BooleanField(default=False, verbose_name='Portaria')),
                ('exclusividade', models.BooleanField(default=False, verbose_name='Exclusividade')),
                ('tempo_exclusividade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de exclusividade')),
                ('iptu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IPTU')),
                ('angariador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Angariador')),
                ('proprietario', models.ManyToManyField(related_name='imoveis_proprietarios', to='clientes.cliente', verbose_name='Proprietários')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['endereco'],
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Data de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_proposta', models.DateTimeField(verbose_name='Data da proposta')),
                ('valor_proposta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da proposta')),
                ('entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Entrada')),
                ('tipo_entrada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de entrada')),
                ('financiamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Financiamento')),
                ('fgts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='FGTS')),
                ('sinal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sinal')),
                ('tipo_sinal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de sinal')),
                ('veiculo_troca', models.CharField(blank=True, max_length=600, null=True, verbose_name='Veículo na troca')),
                ('condicao_entrega', models.CharField(blank=True, max_length=255, null=True, verbose_name='Condição de entrega')),
                ('ficam_no_imovel', models.TextField(blank=True, null=True, verbose_name='Ficam no imóvel')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='clientes.carteira', verbose_name='Cliente')),
                ('imovel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='imoveis.imoveis', verbose_name='Imóvel')),
                ('imovel_troca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_troca', to='imoveis.imoveis', verbose_name='Imóvel na troca')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['data_proposta'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Data de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_visita', models.DateTimeField(verbose_name='Data da visita')),
                ('confirmacao', models.BooleanField(default=False, verbose_name='Confirmação')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='clientes.carteira', verbose_name='Cliente')),
                ('imovel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='imoveis.imoveis', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['data_visita'],
            },
        ),
    ]
