# Generated by Django 5.1.7 on 2025-03-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_imoveis_chave_imoveis_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor'),
        ),
    ]
