# Generated by Django 5.1.7 on 2025-03-23 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Data de modificação')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=14, null=True, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('profissao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profissão')),
                ('renda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Data de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('origem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origem')),
                ('ticket', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ticket')),
                ('metragem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Metragem')),
                ('regiao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Região')),
                ('quartos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quartos')),
                ('banheiros', models.PositiveIntegerField(blank=True, null=True, verbose_name='Banheiros')),
                ('vagas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vagas')),
                ('tipo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo')),
                ('corretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Corretor')),
                ('clientes', models.ManyToManyField(related_name='carteiras', to='clientes.cliente', verbose_name='Clientes')),
            ],
            options={
                'verbose_name': 'Carteira',
                'verbose_name_plural': 'Carteiras',
            },
        ),
        migrations.CreateModel(
            name='OfertaAtiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Data de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
                ('resultado', models.CharField(max_length=255, verbose_name='Resultado')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente', verbose_name='Cliente')),
                ('corretor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Corretor')),
            ],
            options={
                'verbose_name': 'Oferta Ativa',
                'verbose_name_plural': 'Ofertas Ativas',
                'ordering': ['-criado'],
            },
        ),
        migrations.CreateModel(
            name='Uniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Data de modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_uniao', models.DateField(verbose_name='Data de união')),
                ('regime_uniao', models.CharField(max_length=255, verbose_name='Regime de união')),
                ('cliente1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unioes_como_cliente1', to='clientes.cliente', verbose_name='Cliente 1')),
                ('cliente2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unioes_como_cliente2', to='clientes.cliente', verbose_name='Cliente 2')),
            ],
            options={
                'verbose_name': 'União',
                'verbose_name_plural': 'Uniões',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.uniao', verbose_name='Estado civil'),
        ),
    ]
