# Generated by Django 5.1.7 on 2025-03-24 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Bloqueado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CNH'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='passaporte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Passaporte'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf_nascimento',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF de nascimento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uniao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.uniao', verbose_name='União'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='uniao',
            name='data_uniao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de união'),
        ),
    ]
